# Generated by Django 5.1.1 on 2024-10-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_userprofile_bio'),
        ('quizapp', '0005_question_remove_quizattempt_question_number_and_more'),
    ]

    operations = [
    ]
