# Generated by Django 5.1.1 on 2024-10-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_merge_20241012_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='question',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
