# Generated by Django 5.1.1 on 2024-10-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_question_remove_quizattempt_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question'),
        ),
    ]
