# Generated by Django 5.1.1 on 2024-10-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_alter_quizattempt_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='statistic_correct_answer',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='question',
            name='statistic_question',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
