# Generated by Django 5.1.1 on 2024-10-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_question_statistic_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statistic_correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='statistic_question',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
