# Generated by Django 5.1.1 on 2024-10-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_alter_question_statistic_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_completed_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
