# Generated by Django 5.1.1 on 2024-10-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0014_quizattempt_actual_quizattempt_predicted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
    ]
